name: Build and deploy Next.js app to Azure Web App - lifeboard

on:
  push:
    branches:
      - basic-skeleton
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Create tarball
        run: |
          mkdir node-app
          mv .next node-app/
          mv package.json node-app/
          mv package-lock.json node-app/
          tar -czvf next-app.tar.gz node-app

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: next-app.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Extract tarball
        run: |
          mkdir node-app
          tar -xzf next-app.tar.gz -C node-app

      - name: List directory contents
        run: ls -al

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'lifeboard'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7963359798BA470DA5F99A9F5A1C28A1 }}
          package: node-app